import { BrainCircuit, CheckCircle2, LineChart, ShieldAlert, Siren } from "lucide-react";
import type { OddsAnalysis } from "@/lib/ai/odds-engine";
import type { UpsetAnalysis } from "@/lib/ai/upset-engine";
import type { CommercialMatchData } from "@/types/match";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ComplianceDisclaimer } from "@/components/common/ComplianceDisclaimer";

type AIReportProps = { report: CommercialMatchData["report"]; recommendation?: string; oddsAnalysis?: OddsAnalysis; upsetAnalysis?: UpsetAnalysis };

export function AIReport({ report, recommendation = "结合模型估算概率，关注主队方向。", oddsAnalysis, upsetAnalysis }: AIReportProps) {
  return <Card className="border-blue-500/25 bg-gradient-to-br from-[#111d3a] to-[#111827]"><CardHeader><CardTitle className="flex items-center gap-2 text-base text-white"><BrainCircuit className="h-5 w-5 text-blue-400" />Athena 深度分析</CardTitle><p className="text-xs text-slate-500">基于球队状态、攻击效率、防守稳定性、市场数据变化与非主流结果概率生成</p></CardHeader><CardContent className="space-y-5"><div><p className="text-xs font-medium text-blue-300">AI完整报告</p><p className="mt-2 text-sm leading-7 text-slate-300">{report.summary}</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-blue-500/20 bg-blue-500/10 p-4"><p className="text-[11px] text-slate-500">比赛倾向</p><p className="mt-2 text-lg font-semibold text-blue-200">{report.lean}</p></div><div className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-4"><p className="flex items-center gap-1.5 text-[11px] text-slate-500"><ShieldAlert className="h-3.5 w-3.5 text-amber-400" />不确定性提醒</p><p className="mt-2 text-sm font-medium leading-6 text-amber-200">{report.risk}</p></div><div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4"><p className="flex items-center gap-1.5 text-[11px] text-slate-500"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" />模型观点</p><p className="mt-2 text-sm font-medium leading-6 text-emerald-200">{recommendation}</p></div></div>{oddsAnalysis && upsetAnalysis && <div className="grid gap-3 border-t border-white/10 pt-5 sm:grid-cols-2"><div className="rounded-xl border border-violet-500/20 bg-violet-500/10 p-4"><p className="flex items-center gap-1.5 text-[11px] text-slate-500"><LineChart className="h-3.5 w-3.5 text-violet-300" />市场数据变化判断</p><p className="mt-2 font-semibold text-violet-200">{oddsAnalysis.recommendation}</p><p className="mt-2 text-xs leading-5 text-slate-400">{oddsAnalysis.signal}</p></div><div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4"><p className="flex items-center gap-1.5 text-[11px] text-slate-500"><Siren className="h-3.5 w-3.5 text-red-300" />非主流结果概率</p><p className="mt-2 font-semibold text-red-200">{upsetAnalysis.underdog} · {upsetAnalysis.upsetProbability}%</p><p className="mt-2 text-xs leading-5 text-slate-400">{upsetAnalysis.reason}</p></div></div>}<ComplianceDisclaimer /></CardContent></Card>;
}
