import { History, Trophy } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import type { MatchDetailData } from "@/types/match";
import { SectionHeader } from "@/components/match/SectionHeader";

const copy = { title: "\u5386\u53f2\u4ea4\u950b", description: "\u6700\u8fd1 5 \u6b21\u4ea4\u950b\u7ed3\u679c\u4e0e\u7edf\u8ba1\u6c47\u603b\u3002", win: "\u80dc", draw: "\u5e73\u5c40", matches: "\u573a", averageGoals: "\u573a\u5747\u603b\u8fdb\u7403", bothScored: "\u53cc\u65b9\u90fd\u6709\u8fdb\u7403" };

export function HeadToHead({ match }: { match: MatchDetailData }) {
  const summary = match.headToHeadSummary;
  return <section id="head-to-head" className="scroll-mt-24"><SectionHeader icon={History} title={copy.title} description={copy.description} /><Card><CardContent className="p-5 sm:p-6"><div className="mb-5 grid grid-cols-3 gap-2 rounded-xl border border-slate-800 bg-slate-900/40 p-4 text-center"><div><p className="text-[11px] text-slate-500">{match.home.name}</p><p className="mt-1 text-xl font-semibold text-blue-300">{summary.homeWins}</p><p className="text-[10px] text-slate-600">{copy.win}</p></div><div><p className="text-[11px] text-slate-500">{copy.draw}</p><p className="mt-1 text-xl font-semibold text-slate-200">{summary.draws}</p><p className="text-[10px] text-slate-600">{copy.matches}</p></div><div><p className="text-[11px] text-slate-500">{match.away.name}</p><p className="mt-1 text-xl font-semibold text-green-300">{summary.awayWins}</p><p className="text-[10px] text-slate-600">{copy.win}</p></div></div><div className="grid gap-6 lg:grid-cols-[1fr_0.75fr]"><div className="space-y-2">{match.headToHead.map((item) => <div key={item.date} className="flex items-center gap-3 rounded-lg border border-slate-800 bg-slate-900/30 px-3 py-2.5 text-xs"><span className="w-20 shrink-0 text-slate-600">{item.date}</span><span className="min-w-0 flex-1 truncate text-right text-slate-300">{item.home}</span><span className="rounded bg-slate-800 px-2.5 py-1 font-semibold text-white">{item.score}</span><span className="min-w-0 flex-1 truncate text-slate-300">{item.away}</span></div>)}</div><div className="grid grid-cols-2 gap-3 self-start"><div className="rounded-lg border border-slate-800 p-3"><Trophy className="h-4 w-4 text-amber-400" /><p className="mt-3 text-[10px] text-slate-500">{copy.averageGoals}</p><p className="mt-1 text-lg font-semibold text-white">{summary.averageGoals}</p></div><div className="rounded-lg border border-slate-800 p-3"><Trophy className="h-4 w-4 text-blue-400" /><p className="mt-3 text-[10px] text-slate-500">{copy.bothScored}</p><p className="mt-1 text-lg font-semibold text-white">{summary.bothScored}%</p></div></div></div></CardContent></Card></section>;
}
